@extends('public.layouts.app')

@section('content')
<!-- Multi-Banner Promotion Section - JakartaNotebook Style -->
<div class="w-screen relative left-1/2 -ml-[50vw] mb-10 bg-gray-50 py-6">
    <div class="w-full px-0">
        <div class="max-w-full grid grid-cols-1 lg:grid-cols-3 gap-4" style="padding-left: 0; padding-right: 0;">
            <!-- Left: Main Banner Carousel (2/3 width on desktop, full width on mobile) -->
            <div class="lg:col-span-2 relative overflow-hidden">
                <div class="relative w-full overflow-hidden">
                    <div id="banner-carousel" class="flex gap-4">
                        <!-- Main banners will be rendered by JavaScript -->
                    </div>

                    <!-- Navigation Arrows -->
                    <button id="banner-prev" class="absolute left-2 top-1/2 -translate-y-1/2 bg-white rounded-full p-2 shadow-lg hover:bg-gray-100 transition-colors z-10">
                        <svg class="w-5 h-5 text-gray-700" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                        </svg>
                    </button>
                    <button id="banner-next" class="absolute right-2 top-1/2 -translate-y-1/2 bg-white rounded-full p-2 shadow-lg hover:bg-gray-100 transition-colors z-10">
                        <svg class="w-5 h-5 text-gray-700" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                        </svg>
                    </button>

                    <!-- Dots Indicator -->
                    <div class="flex justify-center gap-2 mt-3" id="banner-dots">
                        <!-- Dots will be generated by JavaScript -->
                    </div>
                </div>
            </div>

            <!-- Right: Small Promotional Banners (1/3 width on desktop, full width horizontal row on mobile) -->
            <div class="lg:col-span-1" id="side-banners-container">
                <!-- Side banners will be rendered by JavaScript -->
            </div>
        </div>
    </div>
</div>

<style>
    #banner-carousel {
        transition: transform 0.5s cubic-bezier(0.4, 0, 0.2, 1);
        display: flex;
        width: max-content; /* Allow carousel to be wider than container */
    }
    
    .promo-banner {
        user-select: none;
        flex-shrink: 0;
        width: 100%;
    }
    
    .category-overlay:hover {
        background-color: var(--hover-color, rgba(59, 130, 246, 0.3)) !important;
    }
    
    /* Side banners styling - responsive */
    #side-banners-container {
        display: flex;
        flex-direction: row; /* Horizontal on mobile/tablet */
        gap: 12px;
        height: auto;
    }
    
    @media (min-width: 768px) {
        #side-banners-container {
            flex-direction: row; /* Horizontal on tablet */
        }
    }
    
    #side-banners-container a {
        flex: 1;
        min-height: 180px;
    }
    
    @media (min-width: 1024px) {
        #side-banners-container {
            flex-direction: column; /* Vertical stack on desktop */
            /* Main banner height = (2/3 of container width) * 0.3333 = container_width * 0.2222 */
            /* Side container width = (1/3 of container width) = container_width * 0.3333 */
            /* To match main banner height with side container: aspect-ratio = 0.3333 : 0.2222 = 3:2 = 1.5:1 */
            aspect-ratio: 1.5 / 1;
        }
        
        #side-banners-container a {
            min-height: 0;
            flex: 1;
        }
    }
</style>

<!-- Categories -->
<h1 class="text-3xl font-bold mb-6">Shop by Category</h1>
<div id="categories-container" class="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-6 mb-10">
    <!-- Categories will be rendered by JavaScript -->
</div>

<!-- Featured Products -->
<h2 class="text-2xl font-bold mb-6">Featured Products</h2>
<div id="featured-products" class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 md:gap-6">
</div>
@endsection

@push('js')
<script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script>
    // Banner data - can be replaced with API call later
    const bannerData = [
        { id: 1, image: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=1200&h=675&fit=crop', badge: 'FLASH SALE', badgeColor: 'red-600', title: 'Up to 50% OFF', description: 'Limited Time Offer', gradientFrom: 'red-500', gradientTo: 'orange-500', link: '#' },
        { id: 2, image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=1200&h=675&fit=crop', badge: 'NEW ARRIVALS', badgeColor: 'blue-600', title: 'Latest Collection', description: 'Shop Now & Save', gradientFrom: 'blue-500', gradientTo: 'purple-500', link: '#' },
        { id: 3, image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1200&h=675&fit=crop', badge: 'SPECIAL DEAL', badgeColor: 'green-600', title: '30% Discount', description: 'On Selected Items', gradientFrom: 'green-500', gradientTo: 'teal-500', link: '#' },
        { id: 4, image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&h=675&fit=crop', badge: 'WEEKEND SALE', badgeColor: 'yellow-600', title: 'Buy 2 Get 1 Free', description: 'This Weekend Only', gradientFrom: 'yellow-500', gradientTo: 'orange-500', link: '#' },
        { id: 5, image: 'https://images.unsplash.com/photo-1600298881974-6be191ceeda1?w=1200&h=675&fit=crop', badge: 'MEGA SALE', badgeColor: 'pink-600', title: 'Save Up to 70%', description: 'Don\'t Miss Out', gradientFrom: 'pink-500', gradientTo: 'red-500', link: '#' },
        { id: 6, image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&h=675&fit=crop', badge: 'PREMIUM DEAL', badgeColor: 'indigo-600', title: '40% OFF Today', description: 'Premium Collection', gradientFrom: 'indigo-500', gradientTo: 'purple-500', link: '#' },
        { id: 7, image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1200&h=675&fit=crop', badge: 'SUMMER SALE', badgeColor: 'cyan-600', title: 'Hot Summer Deals', description: 'Stay Cool & Save', gradientFrom: 'cyan-500', gradientTo: 'blue-500', link: '#' },
        { id: 8, image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=1200&h=675&fit=crop', badge: 'LIMITED TIME', badgeColor: 'amber-600', title: '60% Discount', description: 'Ends Soon!', gradientFrom: 'amber-500', gradientTo: 'yellow-500', link: '#' },
        { id: 9, image: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=1200&h=675&fit=crop', badge: 'BLACK FRIDAY', badgeColor: 'violet-600', title: 'Massive Savings', description: 'Best Deals Ever', gradientFrom: 'violet-500', gradientTo: 'purple-500', link: '#' },
        { id: 10, image: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=1200&h=675&fit=crop', badge: 'ECO FRIENDLY', badgeColor: 'emerald-600', title: 'Green Collection', description: 'Sustainable Shopping', gradientFrom: 'emerald-500', gradientTo: 'teal-500', link: '#' },
        { id: 11, image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=1200&h=675&fit=crop', badge: 'VALENTINE\'S', badgeColor: 'rose-600', title: 'Love Collection', description: 'Perfect Gifts', gradientFrom: 'rose-500', gradientTo: 'pink-500', link: '#' },
        { id: 12, image: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=1200&h=675&fit=crop', badge: 'CLEARANCE', badgeColor: 'sky-600', title: 'Up to 80% OFF', description: 'Final Clearance Sale', gradientFrom: 'sky-500', gradientTo: 'blue-500', link: '#' }
    ];

    // Category data - can be replaced with API call later
    const categoryData = [
        { id: 1, name: 'Shoes', slug: 'shoes', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop', hoverColor: 'red-500' },
        { id: 2, name: 'Watches', slug: 'watches', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop', hoverColor: 'green-500' },
        { id: 3, name: 'Shirts', slug: 'shirts', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop', hoverColor: 'yellow-500' },
        { id: 4, name: 'Accessories', slug: 'accessories', image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=500&h=500&fit=crop', hoverColor: 'purple-500' }
    ];

    // Color mapping for Tailwind classes
    const colorMap = {
        'red-500': '#ef4444', 'red-600': '#dc2626',
        'orange-500': '#f97316', 'orange-600': '#ea580c',
        'blue-500': '#3b82f6', 'blue-600': '#2563eb',
        'purple-500': '#a855f7', 'purple-600': '#9333ea',
        'green-500': '#22c55e', 'green-600': '#16a34a', 'teal-500': '#14b8a6', 'teal-600': '#0d9488',
        'yellow-500': '#eab308', 'yellow-600': '#ca8a04', 'amber-500': '#f59e0b', 'amber-600': '#d97706',
        'pink-500': '#ec4899', 'pink-600': '#db2777', 'rose-500': '#f43f5e', 'rose-600': '#e11d48',
        'indigo-500': '#6366f1', 'indigo-600': '#4f46e5',
        'cyan-500': '#06b6d4', 'cyan-600': '#0891b2',
        'violet-500': '#8b5cf6', 'violet-600': '#7c3aed',
        'emerald-500': '#10b981', 'emerald-600': '#059669',
        'sky-500': '#0ea5e9', 'sky-600': '#0284c7'
    };

    // Banner rendering utility
    const BannerUtils = {
        // Render main large banner for carousel
        renderMainBanner: function(banner) {
            const gradientFromColor = colorMap[banner.gradientFrom] || colorMap['blue-500'];
            const gradientToColor = colorMap[banner.gradientTo] || colorMap['purple-500'];
            const badgeBgColor = colorMap[banner.badgeColor] || colorMap['blue-600'];
            
            return `
                <div class="promo-banner flex-shrink-0 w-full" data-banner-id="${banner.id}">
                    <a href="${banner.link}" class="block relative rounded-lg overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-300 w-full">
                        <div class="relative w-full" style="background: linear-gradient(to bottom right, ${gradientFromColor}, ${gradientToColor}); padding-bottom: 33.33%;">
                            <img src="${banner.image}" alt="${banner.title}" class="absolute top-0 left-0 w-full h-full object-cover" style="opacity: 0.8;" loading="eager" onerror="this.onerror=null; this.src='data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%221200%22 height=%22675%22%3E%3Crect fill=%22%23ddd%22 width=%221200%22 height=%22675%22/%3E%3Ctext fill=%22%23999%22 x=%2250%25%22 y=%2250%25%22 text-anchor=%22middle%22 dy=%22.3em%22%3EImage not available%3C/text%3E%3C/svg%3E';">
                            <div class="absolute inset-0 flex flex-col justify-center items-center p-6 text-white" style="z-index: 10;">
                                <div class="px-4 py-2 rounded-full mb-3" style="background-color: ${badgeBgColor};">
                                    <span class="text-sm font-bold">${banner.badge}</span>
                                </div>
                                <h2 class="text-2xl md:text-3xl font-bold mb-2 text-center">${banner.title}</h2>
                                <p class="text-sm md:text-base text-center">${banner.description}</p>
                            </div>
                        </div>
                    </a>
                </div>
            `;
        },
        // Render small side banner
        renderSideBanner: function(banner) {
            const gradientFromColor = colorMap[banner.gradientFrom] || colorMap['blue-500'];
            const gradientToColor = colorMap[banner.gradientTo] || colorMap['purple-500'];
            const badgeBgColor = colorMap[banner.badgeColor] || colorMap['blue-600'];
            
            return `
                <a href="${banner.link}" class="block relative rounded-lg overflow-hidden shadow-md hover:shadow-lg transition-shadow duration-300 flex-1 h-full" style="background: linear-gradient(to bottom right, ${gradientFromColor}, ${gradientToColor});">
                    <div class="relative w-full h-full p-4 flex flex-col justify-between">
                        <img src="${banner.image}" alt="${banner.title}" class="absolute top-0 left-0 w-full h-full object-cover" style="opacity: 0.7;" loading="eager">
                        <div class="relative z-10 text-white">
                            <div class="px-2 py-1 rounded-full mb-2 inline-block" style="background-color: ${badgeBgColor};">
                                <span class="text-xs font-bold">${banner.badge}</span>
                            </div>
                            <h3 class="text-lg font-bold mb-1">${banner.title}</h3>
                            <p class="text-xs">${banner.description}</p>
                        </div>
                    </div>
                </a>
            `;
        },
        renderMainCarousel: function(banners, container) {
            let html = '';
            banners.forEach(banner => {
                html += this.renderMainBanner(banner);
            });
            $(container).html(html);
        },
        renderSideBanners: function(banners, container) {
            let html = '';
            banners.forEach(banner => {
                html += this.renderSideBanner(banner);
            });
            $(container).html(html);
        }
    };

    // Category rendering utility
    const CategoryUtils = {
        renderCategory: function(category) {
            const hoverColor = colorMap[category.hoverColor] || colorMap['blue-500'];
            
            return `
                <a href="/category/${category.slug}" class="group relative overflow-hidden rounded-lg aspect-square shadow-md">
                    <img src="${category.image}" alt="${category.name}" class="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110">
                    <div class="absolute inset-0 transition-all duration-300 flex items-center justify-center category-overlay" style="background-color: ${hoverColor}00;" data-hover-color="${hoverColor}4d">
                        <span class="text-white font-bold text-xl opacity-0 group-hover:opacity-100 transition-opacity duration-300">${category.name}</span>
                    </div>
                </a>
            `;
        },
        renderAll: function(categories, container) {
            let html = '';
            categories.forEach(category => {
                html += this.renderCategory(category);
            });
            $(container).html(html);
        }
    };

    // Product utilities
    const ProductUtils = {
        // Calculate original price from discount
        calculateOriginalPrice: function(price, discountPercent) {
            return price / (1 - (discountPercent / 100));
        },
        
        // Generate star rating HTML
        generateStarRating: function(rating, size = 'w-4 h-4') {
            const fullStars = Math.floor(rating);
            const hasHalfStar = (rating - fullStars) >= 0.5;
            let html = '<div class="flex items-center">';
            
            for (let i = 1; i <= 5; i++) {
                if (i <= fullStars) {
                    html += `<svg class="${size} text-yellow-400 fill-current" viewBox="0 0 20 20"><path d="M10 15l-5.878 3.09 1.123-6.545L.489 6.91l6.572-.955L10 0l2.939 5.955 6.572.955-4.756 4.635 1.123 6.545z"/></svg>`;
                } else if (i === fullStars + 1 && hasHalfStar) {
                    html += `<svg class="${size} text-yellow-400 fill-current" viewBox="0 0 20 20"><path d="M10 0l2.939 5.955 6.572.955-4.756 4.635 1.123 6.545L10 15l-5.878-3.09 1.123-6.545L.489 6.91l6.572-.955L10 0z"/></svg>`;
                } else {
                    html += `<svg class="${size} text-gray-300 fill-current" viewBox="0 0 20 20"><path d="M10 15l-5.878 3.09 1.123-6.545L.489 6.91l6.572-.955L10 0l2.939 5.955 6.572.955-4.756 4.635 1.123 6.545z"/></svg>`;
                }
            }
            html += '</div>';
            return html;
        },
        
        // Render product card
        renderProductCard: function(product, productUrl) {
            const discountPercent = product.discount || 25;
            const rating = product.rating || 4.5;
            const originalPrice = this.calculateOriginalPrice(product.price, discountPercent);
            const productId = product.id;
            
            return `
                <div class="group bg-white rounded-lg shadow-md overflow-hidden hover:shadow-xl transition-shadow duration-300 relative">
                    <div class="relative overflow-hidden aspect-square">
                        <img src="${product.image}" alt="${product.name}" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-300">
                        <div class="absolute top-2 left-2 bg-red-500 text-white px-2 py-1 rounded-md text-xs font-bold z-10">
                            ${discountPercent}% OFF
                        </div>
                        <button class="absolute top-2 right-2 w-10 h-10 bg-white rounded-full shadow-md flex items-center justify-center hover:bg-red-50 transition-colors wishlist-btn" data-product-id="${productId}" onclick="event.preventDefault(); toggleWishlist(${productId});">
                            <svg class="w-5 h-5 text-gray-400 wishlist-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
                            </svg>
                        </button>
                    </div>
                    <div class="p-4">
                        <a href="${productUrl}">
                            <h3 class="font-semibold text-gray-900 mb-1">${product.name}</h3>
                        </a>
                        <div class="flex items-center gap-1 mb-2">
                            ${this.generateStarRating(rating)}
                            <span class="text-xs text-gray-500">(${rating.toFixed(1)})</span>
                        </div>
                        <div class="flex items-center gap-2">
                            <p class="text-gray-400 font-medium line-through">$${originalPrice.toFixed(2)}</p>
                            <p class="text-gray-900 font-bold">$${product.price.toFixed(2)}</p>
                        </div>
                    </div>
                </div>
            `;
        }
    };
    
    // Load featured products (replace with your API call)
    $(function() {
        // Initialize banners and categories from data
        // TODO: Replace with API calls later
        // Example: $.get('/api/banners', function(data) { 
        //     BannerUtils.renderAll(data, '#banner-carousel');
        //     initializeCarousel();
        // });
        
        // Split banners: first 4 for main carousel, 3 for side banners
        const mainBanners = bannerData.slice(0, 4);
        const sideBanners = bannerData.slice(4, 7); // Only 3 side banners
        
        // Render main carousel and side banners
        BannerUtils.renderMainCarousel(mainBanners, '#banner-carousel');
        BannerUtils.renderSideBanners(sideBanners, '#side-banners-container');
        CategoryUtils.renderAll(categoryData, '#categories-container');
        
        // Initialize carousel
        setTimeout(function() {
            // Multi-Banner Carousel with Drag Support
            const $carousel = $('#banner-carousel');
            let $banners = $('.promo-banner');
            const $prevBtn = $('#banner-prev');
            const $nextBtn = $('#banner-next');
            const $dotsContainer = $('#banner-dots');
            
            let currentIndex = 0;
            let currentOffset = 0;
            let autoScrollInterval = null;
        
        const bannersPerView = () => {
            // Always show 1 banner per slide (1 dot = 1 banner)
            return 1;
        };
        
        // Create dots based on pages (not individual banners)
        function createDots() {
            $dotsContainer.empty();
            const perView = bannersPerView();
            const totalPages = Math.ceil($banners.length / perView);
            
            for (let i = 0; i < totalPages; i++) {
                $dotsContainer.append(`<button class="banner-dot w-2 h-2 rounded-full bg-gray-300 transition-all duration-300 ${i === 0 ? 'bg-red-500 w-6' : ''}" data-index="${i}"></button>`);
            }
        }
        
        createDots();
        let $dots = $('.banner-dot');
        
        // Set banner widths based on visible container
        function setBannerWidths() {
            const perView = bannersPerView();
            const containerWidth = $carousel.parent().width();
            const gap = 16; // gap-4 = 1rem = 16px
            const totalGaps = (perView - 1) * gap;
            const bannerWidth = (containerWidth - totalGaps) / perView;
            
            $banners.css('width', `${bannerWidth}px`);
        }
        
        // Set initial banner widths before first update
        setBannerWidths();
        
        // Update carousel position with smooth animation
        function updateCarousel(animate = true) {
            const perView = bannersPerView();
            const maxIndex = Math.max(0, $banners.length - perView);
            currentIndex = Math.min(currentIndex, maxIndex);
            currentIndex = Math.max(0, currentIndex);
            
            // Calculate offset: move by one banner width + gap
            const containerWidth = $carousel.parent().width();
            const gap = 16; // gap-4 = 1rem = 16px
            const totalGaps = (perView - 1) * gap;
            const bannerWidth = (containerWidth - totalGaps) / perView;
            const targetOffset = -currentIndex * (bannerWidth + gap);
            
            $carousel.css('transform', `translateX(${targetOffset}px)`);
            
            currentOffset = targetOffset;
            
            // Update dots
            $dots.removeClass('bg-red-500 w-6').addClass('bg-gray-300 w-2');
            const activeDotIndex = Math.floor(currentIndex / perView);
            if ($dots.eq(activeDotIndex).length) {
                $dots.eq(activeDotIndex).removeClass('bg-gray-300 w-2').addClass('bg-red-500 w-6');
            }
        }
        
        // Next button
        $nextBtn.on('click', function() {
            const perView = bannersPerView();
            const maxIndex = Math.max(0, $banners.length - perView);
            if (currentIndex < maxIndex) {
                currentIndex = Math.min(currentIndex + perView, maxIndex);
                updateCarousel(true);
            } else {
                currentIndex = 0; // Loop back to start
                updateCarousel(true);
            }
            resetAutoScroll(); // Reset autoscroll when user interacts
        });
        
        // Prev button
        $prevBtn.on('click', function() {
            const perView = bannersPerView();
            if (currentIndex > 0) {
                currentIndex = Math.max(0, currentIndex - perView);
                updateCarousel(true);
            } else {
                currentIndex = Math.max(0, $banners.length - perView); // Loop to last
                updateCarousel(true);
            }
            resetAutoScroll(); // Reset autoscroll when user interacts
        });
        
        // Dot navigation
        $dots.on('click', function() {
            const perView = bannersPerView();
            const index = $(this).data('index');
            currentIndex = index * perView;
            updateCarousel(true);
            resetAutoScroll(); // Reset autoscroll when user interacts
        });
        
        // Auto-scroll functionality
        function startAutoScroll() {
            // Clear any existing interval
            if (autoScrollInterval) {
                clearInterval(autoScrollInterval);
            }
            
            // Set new interval: auto-scroll every 5 seconds
            autoScrollInterval = setInterval(function() {
                const perView = bannersPerView();
                const maxIndex = Math.max(0, $banners.length - perView);
                
                // Move to next slide, or loop back to first
                if (currentIndex < maxIndex) {
                    currentIndex += perView;
                } else {
                    currentIndex = 0; // Loop back to start
                }
                
                updateCarousel(true);
            }, 5000); // 5 seconds
        }
        
        function stopAutoScroll() {
            if (autoScrollInterval) {
                clearInterval(autoScrollInterval);
                autoScrollInterval = null;
            }
        }
        
        function resetAutoScroll() {
            stopAutoScroll();
            startAutoScroll();
        }
        
        // Pause autoscroll on hover
        $carousel.parent().on('mouseenter', function() {
            stopAutoScroll();
        }).on('mouseleave', function() {
            startAutoScroll();
        });
        
        // Start autoscroll
        startAutoScroll();
        
        // Handle window resize
        $(window).on('resize', function() {
            setBannerWidths(); // Recalculate banner widths on resize
            createDots();
            $dots = $('.banner-dot');
            currentIndex = 0; // Reset to first page on resize
            updateCarousel(true);
            
            // Re-attach dot click handlers
            $dots.off('click').on('click', function() {
                const perView = bannersPerView();
                const index = $(this).data('index');
                currentIndex = index * perView;
                updateCarousel(true);
            });
        });
        
        // Prevent image drag
        $carousel.find('img').on('dragstart', function(e) {
            e.preventDefault();
        });
        
            // Initialize
            updateCarousel(false);
        }, 50); // Small delay to ensure DOM is updated
        
        // Example: Load products from API
        // Replace this with your actual API endpoint
        /*
        $.get('/api/featured-products', function(products) {
            const $container = $('#featured-products');
            $container.empty();
            products.forEach(function(product) {
                const productUrl = `/product/${product.id}`;
                $container.append(ProductUtils.renderProductCard(product, productUrl));
            });
            // Initialize wishlist state
            initWishlistState();
        });
        */
        
        // For demo purposes, using sample data
        const sampleProducts = [
            { id: 1, name: 'Running Shoes', price: 89.99, discount: 25, rating: 4.5, image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop' },
            { id: 5, name: 'Classic Watch', price: 199.99, discount: 20, rating: 4.8, image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop' },
            { id: 9, name: 'Cotton T-Shirt', price: 24.99, discount: 30, rating: 4.2, image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop' },
            { id: 13, name: 'Leather Belt', price: 45.99, discount: 15, rating: 4.6, image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=500&h=500&fit=crop' }
        ];
        
        const $container = $('#featured-products');
        sampleProducts.forEach(function(product) {
            const productUrl = `/product/${product.id}`;
            $container.append(ProductUtils.renderProductCard(product, productUrl));
        });
        
        // Initialize wishlist state
        initWishlistState();
    });
    
    function initWishlistState() {
        const wishlist = JSON.parse(localStorage.getItem('wishlist') || '[]');
        wishlist.forEach(function(productId) {
            const btn = document.querySelector(`.wishlist-btn[data-product-id="${productId}"]`);
            if (btn) {
                const icon = btn.querySelector('.wishlist-icon');
                const path = icon.querySelector('path');
                icon.classList.remove('text-gray-400');
                icon.classList.add('active', 'text-red-500');
                icon.setAttribute('fill', 'currentColor');
                path.setAttribute('stroke', 'none');
                btn.classList.add('bg-red-50');
            }
        });
    }
</script>
@endpush